---
name: Mediathekview Updates

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

# Global environment variable accessible to all jobs and steps
env:
  MV_VERSION_FILE: 'mediathekview.version'

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Read the latest tag from repository Mediathekview
        id: mediathekview_remote
        uses: oprypin/find-latest-tag@dd2729fe78b0bb55523ae2b2a310c6773a652bd1  # v1.1.2
        with:
          # The repository to scan.
          repository: mediathekview/MediathekView
          # We know that all relevant tags have a GitHub release for them.
          releases-only: false

      - name: Read the locally stored version number
        id: mediathekview_local
        run: echo "version=$(cat $MV_VERSION_FILE)" >> $GITHUB_OUTPUT

    outputs:
      mv_local_version: ${{ steps.mediathekview_local.outputs.version }}
      mv_original_version: ${{ steps.mediathekview_remote.outputs.tag }}


  update-version:
    needs: tag-new-versions
    if: ${{ needs.tag-new-versions.outputs.mv_local_version != needs.tag-new-versions.outputs.mv_original_version }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set globals
        id: globals
        shell: bash
        run: |
          echo "NOW=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "MV_VERSION_FILE=$MV_VERSION_FILE" >> $GITHUB_OUTPUT

      - name: Checkout this repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Write new version number to file
        run: echo "${{ needs.tag-new-versions.outputs.mv_original_version }}"  > $MV_VERSION_FILE

      - name: Create Pull Request for the change
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Bump mediathekview/MediathekView in ${{ steps.globals.outputs.MV_VERSION_FILE }}
          signoff: false
          branch: dependabot-mediathekview-${{ needs.tag-new-versions.outputs.mv_original_version }}
          delete-branch: true
          title: 'Bump mediathekview/MediathekView from ${{ needs.tag-new-versions.outputs.mv_local_version }} to ${{ needs.tag-new-versions.outputs.mv_original_version }} in ${{ steps.globals.outputs.MV_VERSION_FILE }}'
          body: |
              Bump mediathekview/MediathekView from ${{ needs.tag-new-versions.outputs.mv_local_version }} to ${{ needs.tag-new-versions.outputs.mv_original_version }}.
          #    - Updated with *today's* date
          labels: |
            dependencies
          draft: false
          assignees: dwydler
